import {KeysEnum} from "../utils/typescript";

/**
 * A work.
 */
export default interface Work {
  /**
   * The year in which this work was created.
   */
  year: number;

  /**
   * The week(s) for which this work is meant.
   *
   * There are frontend and backend validations for this to have at least one entry.
   */
  weekNumbers: string[];

  /**
   * The name of the artist.
   */
  artistName: string;

  /**
   * The title of the work.
   *
   * Max of 128 characters.
   */
  title: string;

  /**
   * The medium of the work.
   *
   * Max of 128 characters.
   */
  medium?: string;

  /**
   * The description of the work.
   *
   * Max of 2048 characters.
   */
  description: string;

  /**
   * If the submission contains text as prose, the prose in the work.
   *
   * Max of 65536 characters (66 KiB uncompressed).
   */
  prose?: string;

  /**
   * A list of URLs related to the content of this work.
   *
   * Order matters and is represented in provided order on the frontend.
   */
  urls: string[];

  /**
   * The thumbnail URL.
   *
   * This is either uploaded manually by the user or generated by our data pipeline.
   */
  thumbnailUrl: string;

  /**
   * Whether or not a post is approved.
   *
   * If the user is not authenticated and a staff user or the user who uploaded the post
   * themselves, these works typically won't appear.
   */
  isApproved: boolean;

  /**
   * The corresponding Discord post's ID, if it exists.
   */
  discordId?: string;
}

/**
 * The keys of {@link Work}.
 */
export const WorkKeys: KeysEnum<Work> = {
  year: true,
  weekNumbers: true,
  artistName: true,
  title: true,
  medium: true,
  description: true,
  prose: true,
  urls: true,
  thumbnailUrl: true,
  isApproved: true,
  discordId: true,
};
