name = "api"
type = "javascript"
workers_dev = true

account_id = "<snip>"

compatibility_date = "2021-12-19"

kv-namespaces = [
  { binding = "REFRESH_KV", id = "<snip>", preview_id = "<snip>" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "./out"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production.vars]
ALLOWED_ORIGIN = "<snip>"
